### PR TITLE
Fix / Compatibility for 1.17 + 1.17.1

### LINKED ISSUE #26: incompatible with spigot 1.17
An error on startup occurs:

```
[10:20:14 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
[10:20:14 WARN]:        at de.gerrygames.viarewind.legacysupport.reflection.ReflectionAPI.getField(ReflectionAPI.java:27)
[10:20:14 WARN]:        at de.gerrygames.viarewind.legacysupport.reflection.ReflectionAPI.getFieldAccessible(ReflectionAPI.java:45)
[10:20:14 WARN]:        at de.gerrygames.viarewind.legacysupport.injector.BoundingBoxFixer.fixLilyPad(BoundingBoxFixer.java:16)
[10:20:14 WARN]:        at de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:38)
[10:20:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[10:20:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[10:20:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1127)
[10:20:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[10:20:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[10:20:14 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.BlockLadder
[10:20:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[10:20:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[10:20:14 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[10:20:14 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[10:20:14 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[10:20:14 WARN]:        at de.gerrygames.viarewind.legacysupport.injector.NMSReflection.getNMSClass(NMSReflection.java:15)
[10:20:14 WARN]:        at de.gerrygames.viarewind.legacysupport.injector.BoundingBoxFixer.fixLadder(BoundingBoxFixer.java:26)
[10:20:14 WARN]:        at de.gerrygames.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:40)
[10:20:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
[10:20:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[10:20:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1127)
[10:20:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[10:20:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[10:20:14 INFO]: Could not fix ladder bounding box.
```

ViaVersion Dump: https://dump.viaversion.com/bd73b743e6d96dfb6b906123d5bbb605efe434814ce70c3604b3850096a4a7e7

Paper Version:

```
> paper version
[10:20:17 INFO]: Checking version, please wait...
[10:20:17 INFO]: This server is running Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Paper-"33d6b6f" (MC: 1.17)
```

This server is running on Java 16.0.1 (Build 16.0.1+9-24)

### PR DESCRIPTION
**Pull request by PierreSchwang**
Adds support for 1.17 and their new packaging conventions / format. 

Fixes #26

### CODE REVIEW

**Comment by creeper123123321** [comment]
I hope it works

**Comment by srnyx** [comment]
https://paste.srnyx.xyz/itisugomez.sql

**Comment by PierreSchwang** [comment]
@srnyx That has nothing to do with the PR at all - Can you tell me what server software + version you are using? Seems like they added a final modifier to the fields which prevents from overriding that.

**Comment by srnyx** [comment]
> @srnyx That has nothing to do with the PR at all - Can you tell me what server software + version you are using? Seems like they added a final modifier to the fields which prevents from overriding that.

Purpur 1.17.1

**Comment by srnyx** [comment]
Oh, I didn't notice this was merged. Should probably switch to `master`

**Comment by PierreSchwang** [comment]
Yup, as I thought, they are final properties now - Are you on the discord? I'm gonna create a fix real quick

**Comment by PierreSchwang** [comment]
Couldn't reproduce that issue with latest builds (Via*, Purpur)

**Pull request merged**
